# Generated by Django 3.1.2 on 2022-02-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=30, null=True)),
                ('Email_id', models.TextField(max_length=50, null=True)),
                ('subject', models.TextField(max_length=200, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
